// <auto-generated />
namespace ElevenFiftySports.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CheckingIfDbUpdateNaming : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CheckingIfDbUpdateNaming));
        
        string IMigrationMetadata.Id
        {
            get { return "202102171922249_CheckingIfDbUpdateNaming"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
